version: "3.4"
services:
 octy:
  build:
   context: .
  container_name: oqtane-web
  image: mkcsas/oqtane-app-web:3
  ports:
  - 5111:5111
  volumes:
  - ./src/:/work



  #working_dir: /work
  #entrypoint: /bin/bash
  #stdin_open: true
  #tty: true