version: "3.4"
services:
 octy:
  build:
   context: .
  container_name: oqtane-web
  image: mkcsas/oqtane-app-web:3
  ports:
  - "0.0.0.0:5999:5999"
  volumes:
  - ./oqtane.framework/:/app



  #working_dir: /work
  #entrypoint: /bin/bash
  #stdin_open: true
  #tty: true