version: "3.4"
services:
 app-oqtane:
  build:
   context: .
  container_name: oqtane-app
  image: mkcsas/app-oqtane:v2
  ports:
  - "0.0.0.0:6001:6001"
 db:
  container_name: oqtane-sql
  image: mkcsas/oqtane-sql-base:v1.0.1
  ports: 
  - "1433:1433"
    



  #working_dir: /work
  #entrypoint: /bin/bash
  #stdin_open: true
  #tty: true